version: '3'

services:
  back:
    build:
      context: ./FastApi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - back
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"