version: '3'

services:
  back:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  # flask:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - back
  db:
    image: mysql:5.7.44
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=usersDb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"