name: Ejecutar pruebas de Python en push

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar el entorno
      run: |
        python --version
        pip --version

    - name: Instala las dependencias
        # Instala las dependencias
        pip install -r requirements.txt
        # Asegúrate de que tienes un archivo requirements.txt con las dependencias de tu proyecto.
    - name: Ejecutar pruebas
      run: |
        # Ejecuta tus pruebas de Python
        pytest
        # Asegúrate de que tengas pytest instalado y configurado para tu proyecto.

    - name: Saludar
      run: echo "Se han ejecutado las pruebas de Python satisfactoriamente"