name: Ejecutar Docker en push

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Iniciar Docker
      run: docker info
    
    - name: Instalar Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Construir imagen e iniciar el Docker
      run: docker-compose up --build
      
    - name: Saludar
      run: echo "Se a detenido la ejecucion de los contenedores"
